kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: sample-app-version2-bc
  namespace: tekton-manual-demo-preprod
  labels:
    app: sample-app-version2-bc
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'sample-manual-app:version2'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:16-ubi8'
      env:
        - name: TITLE
          value: Version2
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/MoOyeg/manual-tekton-approval-task.git'
      ref: working
    contextDir: /sample-app
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
status: {}