kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-pipeline-requisite-binding
  namespace: tekton-manual-demo-preprod
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: tekton-manual-demo-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-pipeline-requisite