kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'allow-pull-from-preprod-to-prod'
  namespace: tekton-manual-demo-preprod
  annotations:
    openshift.io/description: >-
      Allows all pods in this namespace to pull images from this namespace.  It
      is auto-managed by a controller; remove subjects to disable.
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:tekton-manual-demo-prod'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
